import CartProvider from "@/contexts/CartContext";
import SidebarProvider from "@/contexts/SidebarContext";
import ProductProvider from "@/contexts/ProductContext";
import Header from "@/components/Header";
import Basket from "@/components/Basket";
import "./globals.css";

export const metadata = {
  title: "SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <SidebarProvider>
          <ProductProvider>
            <body>
              <Header />
              <Basket />
              {children}
            </body>
          </ProductProvider>
        </SidebarProvider>
      </CartProvider>
    </html>
  );
}
